### ISSUE TITLE
Statement in README about nightly becomes beta

### ISSUE THREAD

**Issue by NikVolf** [dtolnay/rust-faq#4]
> Stable and beta are updated every six weeks, with the current nightly becoming the new beta, and the current beta becoming the new stable

Is this correct? I think there are a lot of things that were only in nightly quite for some time > 6 weeks

**Comment by dtolnay** [comment]
Yes it is correct. Code that lands in nightly will be present in stable after a nightly-to-beta promotion (after 0 to 6 weeks) and a beta-to-stable promotion (another 6 weeks). Once the feature is formally accepted, the feature gate for it is removed and it becomes usable without #![feature(...)] in nightly, then beta, then stable.

**Comment by NikVolf** [comment]
Ah, so it just feature-gating than can stay for a long time, not actual code
